import { Inter } from "next/font/google";
import Head from "next/head";
import { useRouter } from "next/router";
import Banner from "@/Components/Banner/Banner";
// const inter = Inter({ subsets: ["latin"] });
import { dummyHomeData } from "../../dummyData/DummyData";
import { useState } from "react";
export default function Home() {
  const router = useRouter()
  const [homeData, setHomeData] = useState(dummyHomeData)
  return (
    <div>
      <Head>
        <title>Hunting Coder </title>
        <meta name="description" content="generated by Create React app" />
        <link rel="icon" href="next.svg" />
      </Head>
      <main className="container w-full m-auto">
        <h1 className="text-center py-5 text-2xl md:text-3xl lg:text-5xl font-extrabold tracking-widest text-white">
          Hunting Coder
        </h1>
        <hr/>
        <Banner/>
        <div className="grid gap-2 lg:grid-cols-5 md:grid-cols-4 grid-cols-1">
          {
            homeData.map((data)=>(
              <div key={data.id} onClick={()=>router.push(`/blogpost/${data.title}`)} className="border border-gray-900 hover:border-red-50 duration-200 ease-in-out p-4 rounded-xl cursor-pointer">
            <h3 className="text-2xl font-semibold ">{data.title}</h3>
            <p className="line-clamp-5">
             {data.content}
            </p>
          </div>
            ))
          }
          
        </div>
        
      </main>
    </div>
  );
}
